'use client';

import { useState } from 'react';
import { Download, FileText } from 'lucide-react';

export type TemplateKind = 'hw' | 'test';

interface TemplateDownloaderProps {
  kind: TemplateKind;
  studentName: string;
  subject?: string;
  grade?: string;
}

// ─── Template definitions ──────────────────────────────────────────────────

interface Template {
  id: string;
  label: string;
  description: string;
  color: string;
  generate: (info: { student: string; subject: string; grade: string; date: string }) => string;
}

const HEADER_STYLE = `
  @page { size: A4 portrait; margin: 2.54cm 2.54cm 2.54cm 2.54cm; }
  body { font-family: 'Arial', sans-serif; margin: 0; padding: 0; color: #111; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .meta { font-size: 13px; color: #555; margin-bottom: 20px; }
  .field-row { display: flex; gap: 40px; margin-bottom: 16px; }
  .field { flex: 1; border-bottom: 1px solid #333; padding-bottom: 4px; }
  .field label { font-size: 11px; color: #777; display: block; margin-bottom: 2px; }
  hr { border: none; border-top: 2px solid #222; margin: 16px 0; }
  .section-title { font-size: 14px; font-weight: bold; margin: 20px 0 8px; text-transform: uppercase; letter-spacing: 0.5px; }
  .line { border-bottom: 1px solid #ccc; height: 28px; margin-bottom: 4px; }
  .blank-line { display: inline-block; border-bottom: 1px solid #333; min-width: 100px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { border: 1px solid #ccc; padding: 8px 10px; font-size: 13px; text-align: left; }
  th { background: #f5f5f5; font-weight: bold; }
  ol { padding-left: 20px; }
  ol li { margin-bottom: 18px; font-size: 14px; line-height: 1.6; }
  .choice { margin: 4px 0 4px 10px; font-size: 13px; }
  .match-table td { width: 50%; }
  .footer { margin-top: 40px; font-size: 11px; color: #aaa; text-align: center; border-top: 1px solid #eee; padding-top: 12px; }
`;

function wrap(title: string, body: string): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title><style>${HEADER_STYLE}</style></head><body>${body}<div class="footer">Generated by Teacher'sDesk • Print with Ctrl+P</div></body></html>`;
}

function infoHeader(info: { student: string; subject: string; grade: string; date: string }, title: string) {
  return `
    <h1>${title}</h1>
    <div class="meta">Teacher'sDesk</div>
    <hr/>
    <div class="field-row">
      <div class="field"><label>Student Name</label>${info.student}</div>
      <div class="field"><label>Subject</label>${info.subject}</div>
      <div class="field"><label>Grade</label>${info.grade}</div>
      <div class="field"><label>Date</label>${info.date}</div>
    </div>
    <hr/>
  `;
}

// ─── HW Templates ─────────────────────────────────────────────────────────

const HW_TEMPLATES: Template[] = [
  {
    id: 'hw-lined',
    label: 'Lined Worksheet',
    description: 'Simple lined paper with header — ideal for writing tasks.',
    color: '#2563EB',
    generate: (info) => {
      const lines = Array.from({ length: 18 }, () => `<div class="line"></div>`).join('');
      return wrap('Lined Worksheet', infoHeader(info, 'Homework Worksheet') + `<div class="section-title">Write your answers below:</div>${lines}`);
    },
  },
  {
    id: 'hw-fill',
    label: 'Fill in the Blanks',
    description: '10 numbered fill-in-the-blank questions with answer lines.',
    color: '#7C3AED',
    generate: (info) => {
      const qs = Array.from({ length: 10 }, (_, i) =>
        `<li>Question ${i + 1}: ______________ is <span class="blank-line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> and <span class="blank-line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>.<div class="line" style="margin-top:4px"></div></li>`
      ).join('');
      return wrap('Fill in the Blanks', infoHeader(info, 'Homework — Fill in the Blanks') + `<div class="section-title">Fill in the blanks:</div><ol>${qs}</ol>`);
    },
  },
  {
    id: 'hw-mcq',
    label: 'Multiple Choice',
    description: '10 MCQ questions with options A, B, C, D.',
    color: '#059669',
    generate: (info) => {
      const qs = Array.from({ length: 10 }, (_, i) => {
        const choices = ['A', 'B', 'C', 'D'].map(c => `<div class="choice">○ ${c}. ___________________________________</div>`).join('');
        return `<li><strong>Q${i + 1}:</strong> ___________________________________________<br/>${choices}<div style="height:8px"></div></li>`;
      }).join('');
      return wrap('MCQ Homework', infoHeader(info, 'Homework — Multiple Choice Questions') + `<div class="section-title">Choose the correct option:</div><ol>${qs}</ol>`);
    },
  },
  {
    id: 'hw-short',
    label: 'Short Answer',
    description: '6 short-answer questions with space for responses.',
    color: '#D97706',
    generate: (info) => {
      const qs = Array.from({ length: 6 }, (_, i) => {
        const lines = Array.from({ length: 3 }, () => `<div class="line"></div>`).join('');
        return `<li><strong>Q${i + 1}:</strong> ___________________________________________<br/>${lines}<div style="height:8px"></div></li>`;
      }).join('');
      return wrap('Short Answer Homework', infoHeader(info, 'Homework — Short Answer Questions') + `<div class="section-title">Answer the following:</div><ol>${qs}</ol>`);
    },
  },
  {
    id: 'hw-match',
    label: 'Match the Following',
    description: 'Two-column matching exercise with 8 pairs.',
    color: '#DB2777',
    generate: (info) => {
      const rows = Array.from({ length: 8 }, (_, i) => `<tr><td>${i + 1}. _________________________</td><td>${String.fromCharCode(65 + i)}. _________________________</td></tr>`).join('');
      return wrap('Match the Following', infoHeader(info, 'Homework — Match the Following') +
        `<div class="section-title">Match column A with column B:</div>
        <table class="match-table"><thead><tr><th>Column A</th><th>Column B</th></tr></thead><tbody>${rows}</tbody></table>
        <div class="section-title" style="margin-top:24px">Answers:</div>
        ${Array.from({ length: 8 }, (_, i) => `${i + 1} → <span class="blank-line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;`).join('')}`
      );
    },
  },
];

// ─── Test Sheet Templates ──────────────────────────────────────────────────

const TEST_TEMPLATES: Template[] = [
  {
    id: 'test-mcq',
    label: 'Objective (MCQ)',
    description: '20 multiple choice questions — marks per question configurable.',
    color: '#2563EB',
    generate: (info) => {
      const qs = Array.from({ length: 20 }, (_, i) => {
        const choices = ['A', 'B', 'C', 'D'].map(c => `<div class="choice">○ ${c}. _______________________________</div>`).join('');
        return `<li><strong>Q${i + 1}.</strong> ________________________________________________(1 mark)<br/>${choices}<div style="height:6px"></div></li>`;
      }).join('');
      return wrap('MCQ Test', infoHeader(info, 'Test Sheet — Objective Type') +
        `<div style="text-align:right;font-size:13px;margin-bottom:8px"><strong>Total Marks: 20 &nbsp;|&nbsp; Time: ___ mins</strong></div>
        <div class="section-title">Section A — Choose the correct answer: (1×20 = 20)</div><ol>${qs}</ol>`
      );
    },
  },
  {
    id: 'test-short',
    label: 'Short Answer Test',
    description: '10 short-answer questions with 3 lines each.',
    color: '#7C3AED',
    generate: (info) => {
      const qs = Array.from({ length: 10 }, (_, i) => {
        const lines = Array.from({ length: 3 }, () => `<div class="line"></div>`).join('');
        return `<li><strong>Q${i + 1}.</strong> ________________________________________________(2 marks)<br/>${lines}<div style="height:8px"></div></li>`;
      }).join('');
      return wrap('Short Answer Test', infoHeader(info, 'Test Sheet — Short Answer') +
        `<div style="text-align:right;font-size:13px;margin-bottom:8px"><strong>Total Marks: 20 &nbsp;|&nbsp; Time: ___ mins</strong></div>
        <div class="section-title">Section A — Answer the following in 2–3 sentences: (2×10 = 20)</div><ol>${qs}</ol>`
      );
    },
  },
  {
    id: 'test-long',
    label: 'Long Answer Test',
    description: '5 descriptive questions with ample writing space.',
    color: '#059669',
    generate: (info) => {
      const qs = Array.from({ length: 5 }, (_, i) => {
        const lines = Array.from({ length: 8 }, () => `<div class="line"></div>`).join('');
        return `<li><strong>Q${i + 1}.</strong> ________________________________________________(5 marks)<br/>${lines}<div style="height:12px"></div></li>`;
      }).join('');
      return wrap('Long Answer Test', infoHeader(info, 'Test Sheet — Long Answer / Descriptive') +
        `<div style="text-align:right;font-size:13px;margin-bottom:8px"><strong>Total Marks: 25 &nbsp;|&nbsp; Time: ___ mins</strong></div>
        <div class="section-title">Answer the following questions in detail: (5×5 = 25)</div><ol>${qs}</ol>`
      );
    },
  },
  {
    id: 'test-mixed',
    label: 'Mixed Format',
    description: 'MCQ + Short Answer + Long Answer combined.',
    color: '#D97706',
    generate: (info) => {
      const mcq = Array.from({ length: 10 }, (_, i) =>
        `<li>Q${i + 1}. ___________________________ &nbsp; ○ A. _________ &nbsp; ○ B. _________ &nbsp; ○ C. _________ &nbsp; ○ D. _________</li>`
      ).join('');
      const shortAns = Array.from({ length: 5 }, (_, i) => {
        const lines = Array.from({ length: 3 }, () => `<div class="line"></div>`).join('');
        return `<li><strong>Q${i + 1}.</strong> _______________________________________________ (2 marks)<br/>${lines}<div style="height:6px"></div></li>`;
      }).join('');
      const longAns = Array.from({ length: 3 }, (_, i) => {
        const lines = Array.from({ length: 7 }, () => `<div class="line"></div>`).join('');
        return `<li><strong>Q${i + 1}.</strong> _______________________________________________ (5 marks)<br/>${lines}<div style="height:10px"></div></li>`;
      }).join('');
      return wrap('Mixed Test', infoHeader(info, 'Test Sheet — Mixed Format') +
        `<div style="text-align:right;font-size:13px;margin-bottom:8px"><strong>Total Marks: 35 &nbsp;|&nbsp; Time: ___ mins</strong></div>
        <div class="section-title">Section A — MCQ (1×10 = 10)</div><ol>${mcq}</ol>
        <div class="section-title">Section B — Short Answer (2×5 = 10)</div><ol>${shortAns}</ol>
        <div class="section-title">Section C — Long Answer (5×3 = 15)</div><ol>${longAns}</ol>`
      );
    },
  },
  {
    id: 'test-truefalse',
    label: 'True / False',
    description: '15 true/false statements with a bonus short-answer.',
    color: '#DB2777',
    generate: (info) => {
      const stmts = Array.from({ length: 15 }, (_, i) =>
        `<tr><td>${i + 1}.</td><td>____________________________________________________________</td><td>True &nbsp;/&nbsp; False</td></tr>`
      ).join('');
      const lines = Array.from({ length: 5 }, () => `<div class="line"></div>`).join('');
      return wrap('True/False Test', infoHeader(info, 'Test Sheet — True / False') +
        `<div style="text-align:right;font-size:13px;margin-bottom:8px"><strong>Total Marks: 20 &nbsp;|&nbsp; Time: ___ mins</strong></div>
        <div class="section-title">Section A — Circle True or False: (1×15 = 15)</div>
        <table><thead><tr><th>#</th><th>Statement</th><th>Answer</th></tr></thead><tbody>${stmts}</tbody></table>
        <div class="section-title" style="margin-top:20px">Section B — Short Answer: (5 marks)</div>
        <p style="font-size:13px">Explain any one statement from above in your own words:</p>${lines}`
      );
    },
  },
];

// ─── Component ─────────────────────────────────────────────────────────────

export default function TemplateDownloader({ kind, studentName, subject = '', grade = '' }: TemplateDownloaderProps) {
  const templates = kind === 'hw' ? HW_TEMPLATES : TEST_TEMPLATES;

  // Modal state
  const [selected, setSelected] = useState<Template | null>(null);
  const [format, setFormat] = useState<'pdf' | 'word'>('pdf');
  const [downloading, setDownloading] = useState(false);

  function buildInfo() {
    return {
      student: studentName || 'Student Name',
      subject: subject || 'Subject',
      grade: grade ? `Grade ${grade}` : 'Grade',
      date: new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }),
    };
  }

  function handleDownload() {
    if (!selected) return;
    setDownloading(true);
    const html = selected.generate(buildInfo());
    const safeName = `${(studentName || 'Student').replace(/\s+/g, '_')}_${selected.id}_${new Date().toISOString().split('T')[0]}`;

    if (format === 'pdf') {
      // Open in a new window and trigger print → Save as PDF
      const win = window.open('', '_blank');
      if (win) {
        win.document.write(html);
        win.document.close();
        // Small delay so content fully renders before print dialog
        setTimeout(() => {
          win.focus();
          win.print();
          setDownloading(false);
          setSelected(null);
        }, 600);
      } else {
        setDownloading(false);
      }
    } else {
      // Word-compatible HTML (.doc) — Word & LibreOffice open this natively
      const wordHtml = `
        <html xmlns:o="urn:schemas-microsoft-com:office:office"
              xmlns:w="urn:schemas-microsoft-com:office:word"
              xmlns="http://www.w3.org/TR/REC-html40">
        <head>
          <meta charset="UTF-8"/>
          <meta name=ProgId content=Word.Document/>
          <meta name=Generator content="Microsoft Word 15"/>
          <style>
            @page WordSection1 {
              size: 21cm 29.7cm;          /* A4 */
              margin: 2.54cm 2.54cm 2.54cm 2.54cm; /* standard 1-inch margins */
              mso-page-orientation: portrait;
            }
            div.WordSection1 { page: WordSection1; }
            @page { size: A4 portrait; margin: 2.54cm; }
            body { font-family: Arial, sans-serif; margin: 0; padding: 0; color: #111;
                   mso-paper-source: 0; }
            h1 { font-size: 18pt; }
            hr { border-top: 2px solid #222; }
            .field-row { display: flex; gap: 32px; margin-bottom: 12px; }
            .field { flex: 1; border-bottom: 1px solid #333; padding-bottom: 4px; }
            .field label { font-size: 9pt; color: #777; display: block; }
            .section-title { font-size: 11pt; font-weight: bold; margin: 16px 0 6px; text-transform: uppercase; }
            .line { border-bottom: 1px solid #ccc; height: 24px; margin-bottom: 4px; }
            table { width: 100%; border-collapse: collapse; }
            th, td { border: 1px solid #ccc; padding: 6px 8px; font-size: 11pt; }
            th { background: #f0f0f0; }
            ol li { margin-bottom: 16px; font-size: 11pt; }
            .footer { margin-top: 32px; font-size: 9pt; color: #aaa; text-align: center; border-top: 1px solid #eee; padding-top: 8px; }
          </style>
        </head>
        <body>${selected.generate(buildInfo()).replace(/<!DOCTYPE html>.*?<body>/s, '').replace(/<\/body>.*$/s, '')}</body>
        </html>`;

      const blob = new Blob([wordHtml], { type: 'application/msword;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${safeName}.doc`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setDownloading(false);
      setSelected(null);
    }
  }

  return (
    <>
      {/* ── Format-picker modal ── */}
      {selected && (
        <div
          style={{
            position: 'fixed', inset: 0, zIndex: 1000,
            background: 'rgba(0,0,0,0.45)', backdropFilter: 'blur(4px)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}
          onClick={() => setSelected(null)}
        >
          <div
            style={{
              background: 'var(--color-surface)',
              borderRadius: 'var(--radius-xl)',
              padding: '32px 36px',
              width: 380,
              boxShadow: 'var(--shadow-xl)',
              display: 'flex', flexDirection: 'column', gap: 20,
            }}
            onClick={e => e.stopPropagation()}
          >
            {/* Header */}
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span style={{ fontWeight: 700, fontSize: '1.05rem', color: 'var(--color-text-primary)' }}>
                  Download Template
                </span>
                <button
                  id="close-format-modal"
                  onClick={() => setSelected(null)}
                  style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-text-muted)', fontSize: 18, lineHeight: 1, padding: '2px 6px' }}
                  aria-label="Close"
                >✕</button>
              </div>
              <p style={{ margin: '6px 0 0', fontSize: '0.85rem', color: 'var(--color-text-muted)' }}>
                <strong style={{ color: selected.color }}>{selected.label}</strong> — choose a format to download
              </p>
            </div>

            {/* Format options */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {([
                {
                  id: 'pdf' as const,
                  label: 'PDF',
                  desc: 'Opens a print dialog — choose "Save as PDF" from your printer.',
                  icon: '📄',
                },
                {
                  id: 'word' as const,
                  label: 'Word Document (.doc)',
                  desc: 'Downloads a .doc file — open in Microsoft Word or LibreOffice.',
                  icon: '📝',
                },
              ] as const).map(opt => (
                <label
                  key={opt.id}
                  htmlFor={`format-${opt.id}`}
                  style={{
                    display: 'flex', alignItems: 'flex-start', gap: 12,
                    border: `2px solid ${format === opt.id ? 'var(--color-primary)' : 'var(--color-border)'}`,
                    borderRadius: 'var(--radius-lg)',
                    padding: '12px 14px',
                    cursor: 'pointer',
                    background: format === opt.id ? 'var(--color-primary-light)' : 'transparent',
                    transition: 'border-color 0.15s, background 0.15s',
                  }}
                >
                  <input
                    id={`format-${opt.id}`}
                    type="radio"
                    name="dl-format"
                    value={opt.id}
                    checked={format === opt.id}
                    onChange={() => setFormat(opt.id)}
                    style={{ marginTop: 3, accentColor: 'var(--color-primary)' }}
                  />
                  <div>
                    <div style={{ fontWeight: 600, fontSize: '0.9rem', color: 'var(--color-text-primary)' }}>
                      {opt.icon} &nbsp;{opt.label}
                    </div>
                    <div style={{ fontSize: '0.78rem', color: 'var(--color-text-muted)', marginTop: 3 }}>
                      {opt.desc}
                    </div>
                  </div>
                </label>
              ))}
            </div>

            {/* Actions */}
            <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
              <button
                id="cancel-format-modal"
                className="btn btn-secondary btn-sm"
                onClick={() => setSelected(null)}
              >
                Cancel
              </button>
              <button
                id="confirm-download-btn"
                className="btn btn-primary btn-sm"
                onClick={handleDownload}
                disabled={downloading}
                style={{ minWidth: 110, justifyContent: 'center' }}
              >
                {downloading
                  ? <><div className="spinner" style={{ width: 14, height: 14, borderWidth: 2 }} /> Processing…</>
                  : <><Download size={14} /> Download</>}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Template cards ── */}
      <div style={{ marginTop: 'var(--space-8)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 'var(--space-4)' }}>
          <FileText size={18} color="var(--color-text-secondary)" />
          <span style={{ fontWeight: 600, fontSize: '0.95rem', color: 'var(--color-text-primary)' }}>
            Download a Template
          </span>
          <span style={{ fontSize: '0.8rem', color: 'var(--color-text-muted)', marginLeft: 4 }}>
            — pre-formatted printable sheet, pre-filled with student info
          </span>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(210px, 1fr))', gap: 'var(--space-4)' }}>
          {templates.map((t) => (
            <div
              key={t.id}
              style={{
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-lg)',
                padding: 'var(--space-4)',
                background: 'var(--color-surface)',
                display: 'flex',
                flexDirection: 'column',
                gap: 8,
                transition: 'box-shadow 0.18s, transform 0.18s',
              }}
              onMouseEnter={e => { (e.currentTarget as HTMLDivElement).style.boxShadow = 'var(--shadow-md)'; (e.currentTarget as HTMLDivElement).style.transform = 'translateY(-2px)'; }}
              onMouseLeave={e => { (e.currentTarget as HTMLDivElement).style.boxShadow = ''; (e.currentTarget as HTMLDivElement).style.transform = ''; }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <div style={{ width: 10, height: 10, borderRadius: '50%', background: t.color, flexShrink: 0 }} />
                <span style={{ fontWeight: 600, fontSize: '0.875rem', color: 'var(--color-text-primary)' }}>{t.label}</span>
              </div>
              <p style={{ fontSize: '0.78rem', color: 'var(--color-text-muted)', margin: 0, lineHeight: 1.5 }}>{t.description}</p>
              <button
                id={`download-template-${t.id}`}
                className="btn btn-secondary btn-sm"
                style={{ marginTop: 'auto', justifyContent: 'center', borderColor: t.color, color: t.color }}
                onClick={() => { setFormat('pdf'); setSelected(t); }}
                aria-label={`Download ${t.label} template`}
              >
                <Download size={13} /> Download
              </button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}


